improve SSH key handling

diff --git a/psnat3resolver b/psnat3resolver
--- a/psnat3resolver
+++ b/psnat3resolver
@@ -16,6 +16,8 @@ USER_CONF_PATH=$CONF_DIR_PATH/user.conf
 
 source $BASE_CONF_PATH
 source $USER_CONF_PATH
+USER_SSH_KEY_PATH=$SSH_KEY_PATH
+SSH_KEY_PATH=$SELECTED_SSH_KEY_PATH
 
 ACTION=$1
 
@@ -132,18 +134,18 @@ case $ACTION in
     [[ -n "$DO_TOKEN" ]] || { echo "DO_TOKEN is not set. Please set and rerun"; exit 1; }
     [[ -n "$PS_IP" ]] || { echo "PS_IP is not set. Please set and rerun"; exit 1; }
 
-    DEFAULT_SSH_KEY_PATH=/root/.ssh/digital-ocean
-    if [[ ! -n "$SSH_KEY_PATH" ]]; then
-        echo "SSH_KEY_PATH is not set. Using a default SSH key"
-        if [[ ! -f "$DEFAULT_SSH_KEY_PATH" ]]; then
-          echo "Default SSH key is missing. Creating a key..."
-          ssh-keygen -t ed25519 -N "" -f $DEFAULT_SSH_KEY_PATH -C "digital-ocean"
-        fi
-        SSH_KEY_PATH=$DEFAULT_SSH_KEY_PATH
-        echo "SSH_KEY_PATH=$SSH_KEY_PATH" >> $USER_CONF_PATH
+    if [[ -n "$USER_SSH_KEY_PATH" ]]; then
+        [[ -f "$USER_SSH_KEY_PATH"  ]] || { echo "SSH key not found at $USER_SSH_KEY_PATH. Please fix SSH_KEY_PATH and rerun"; exit 1; }
+        SSH_KEY_PATH=$USER_SSH_KEY_PATH
+    else
+      echo "SSH_KEY_PATH is not set. Using a default SSH key"
+      if [[ ! -f "$DEFAULT_SSH_KEY_PATH" ]]; then
+        echo "Default SSH key is missing. Creating a key..."
+        ssh-keygen -t ed25519 -N "" -f $DEFAULT_SSH_KEY_PATH -C "digital-ocean"
+      fi
+      SSH_KEY_PATH=$DEFAULT_SSH_KEY_PATH
     fi
-
-    [[ -f "$SSH_KEY_PATH"  ]] || { echo "SSH key not found at $SSH_KEY_PATH. Please fix SSH_KEY_PATH and rerun"; exit 1; }
+    echo "SELECTED_SSH_KEY_PATH='$SSH_KEY_PATH'" >> $BASE_CONF_PATH
 
     SSH_PUBKEY_PATH="${SSH_KEY_PATH}.pub"
 
